name: CI
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Lint
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/daixiang0/gci@latest

          goimports -w .
          gci write .

          if [ -n "$(git status --porcelain)" ]; then
            echo '🧼 To fix this check, install required tooling and run "goimports -w . && gci write .;"'
            git status # Show the files that failed to pass the check.
            exit 1
          fi
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Test
        run: go test -v ./... -cover
