name: CI
on:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'
      - name: Test & Lint
        run: |
          # Tests
          go test -v ./... -cover
          
          # Lint
          goimports -w .
          
          if [ -n "$(git status --porcelain)" ]; then
            echo '🧼 To fix this check, run "goimports -w .;"'
            git status # Show the files that failed to pass the check.
            exit 1
          fi
